# Linear Algebra

In [2]:
X = [[6, 8, 9, 6, 4],
     [9, 6, 8, 8, 5],
     [5, 5, 6, 8, 9]]

In [3]:
X

[[6, 8, 9, 6, 4], [9, 6, 8, 8, 5], [5, 5, 6, 8, 9]]

In [12]:
Y = [[6, 9, 5],
     [8, 6, 5],
     [9, 8, 6],
     [6, 8, 8],
     [4, 5, 9]]

In [13]:
Y

[[6, 9, 5], [8, 6, 5], [9, 8, 6], [6, 8, 8], [4, 5, 9]]

In [35]:
A = [4,8,7]
B = [2,
     3,
     5]


In [36]:
np.dot(A,B)

67

In [39]:
A = 4
B = [8,
     5,
     1]
A*B

[8, 5, 1, 8, 5, 1, 8, 5, 1, 8, 5, 1]

In [31]:
import numpy as np

In [32]:
P = [3,
     5,
     8]
np.transpose(P)

array([3, 5, 8])

In [40]:
A = 4
P = [3,
     5,
     8]
np.dot(A,B)

array([32, 20,  4])

In [44]:
np.shape(P)

(3L,)

In [46]:
A = [[4,3],
     [6,9]]
B = [[-2,9],
     [-5,2]]
np.subtract(A,B)

array([[ 6, -6],
       [11,  7]])

In [52]:
x =[2,
    8,
    4,
    2]
np.multiply(1/2,x)

array([0, 0, 0, 0])

In [53]:
u = [8,
     1,
     4
]
np.transpose(u)

array([8, 1, 4])

In [55]:
u = [1,
    3,
    -1]
v = [2,
    2,
    4]
w = np.transpose(u)
print w
np.multiply(w,v)

[ 1  3 -1]


array([ 2,  6, -4])